apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx1
  template:
    metadata: # 비워두면 랜덤한 값을 부여
      name: nginx1
      labels:
        app: nginx1
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
